### ISSUE TITLE
export all candidate formulas for mz peak

### ISSUE THREAD

**Issue by deweycw** [EMSL-Computing/CoreMS#18]
It would be great to have the option to export all candidate formulas for an m/z peak. This would help with gap-filling formulas across multiple samples within a dataset.

**Comment by kheal** [comment]
This should be the behavior if the `output_score_method` on the `MolecularFormulaSearchSettings` is set to "All Candidates" (default).  Note that the `add_match_dict_data` method on the `HighResMassSpecExport` acts on the `output_score_method`, not the `score_method`.  If you're seeing this behavior, could you provide an example?

**Comment by deweycw** [comment]
Got it. Setting output_score_method to "All Candidates" works fine. Thanks!
