### ISSUE TITLE
Clarification on molecular formula search settings isProtonated

### ISSUE THREAD

**Issue by Kzra** [EMSL-Computing/CoreMS#9]
Looking in the Molecular Formula Search Settings I am slightly confused about these options: 

```
    # depending on the polarity mode it looks for [M].+ , [M].-
    # query and automatically compile add entry if it doesn't exist
    isRadical: bool = False

    # depending on the polarity mode it looks for [M + H]+ , [M - H]+
    # query and automatically compile and push options if it doesn't exist
    isProtonated: bool = True

    isAdduct: bool = False
```

If I understand correctly, order to search for a formula match to a deprotonated analyte (M-H)- you would set:

```
 isProtonated = True 
 isRadical = True 
 isAdduct = False
```

When `isProtonated = True`, coreMS reads the polarity of the raw spectra and automatically knows to search for [M-H] if the spectra was obtained in negative mode. 

**I initially thought the `isProtonated` boolean refers to [M + H] and thus I was setting this to False to search for deprotonated analytes.** Only after checking my formula assignments did I realize this wasn’t giving me the expected results.   

Maybe extra clarification could be provided in the comments about the isProtonated behaviour? 
Specifically `if True looks for [M + H]+ , [M - H]+ depending on the polarity mode`

Any clarification would be great.

**Comment by corilo** [comment]
When 

isProtonated = True 

I will search for close shell ions ([M + H]+ , [M - H]-, etc)

When 

isRadical = True 

It will search for open shell ions ([M].+ , [M].-, etc)

When  

isAdduct = The

It will search for adducts, with the atoms selected : 

MolecularFormulaSearchSettings.adduct_atoms_neg: tuple = ('Cl', 'Br'), negative mode data

and

MolecularFormulaSearchSettings.adduct_atoms_pos: tuple = ('Na', 'K'), positive mode data

**Comment by Kzra** [comment]
Thanks for clarifying!
